[build]
  publish = "dist"
  command = "npm run build"
  
[build.environment]
  VITE_API_URL = "https://pallybot-api.fly.dev"
  VITE_COUCHDB_URL = "https://couchdb.pallybot.dev"
  VITE_COUCHDB_USER = "pallybot"
  VITE_COUCHDB_PASSWORD = "pallybot-secure-password"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
