[build]
  publish = "dist"
  command = "npm run build"
  
[build.environment]
  VITE_API_URL = "https://pallybot-api.fly.dev"
  # CouchDB environment variables should be set in Netlify UI
  # VITE_COUCHDB_URL
  # VITE_COUCHDB_USER
  # VITE_COUCHDB_PASSWORD
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
